# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudentAttendProgram' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!
 pod 'BaiduMapKit'
 pod 'AFNetworking'
 pod 'FMDB'
 pod 'SDWebImage'
 pod 'SDCycleScrollView'
 pod 'BmobSDK’
 pod ‘Masonry’
 pod 'LBXAlertAction'
 pod ‘Charts’
 pod ‘YYCache’
 pod ‘FMDB’


  # Pods for StudentAttendProgram

  target 'StudentAttendProgramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudentAttendProgramUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
